model:
  base_learning_rate: 4.5e-6
  target: vqgan.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: vqgan.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: vqgan.datasets.dataloader.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 8
    train:
      target: vqgan.datasets.faceshq.FacesHQTrain
      params:
        size: 256
        crop_size: 256
    validation:
      target: vqgan.datasets.faceshq.FacesHQValidation
      params:
        size: 256
        crop_size: 256
